#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"
BACKLOG_FILE="$DOCS_DIR/backlog.md"
STATUS_FILE="$DOCS_DIR/current_status_student_ui_phase1.md"

mkdir -p "$DOCS_DIR"

# If backlog doesn't exist, create a minimal one.
if [ ! -f "$BACKLOG_FILE" ]; then
cat > "$BACKLOG_FILE" <<'MD'
# Smart-Edu Backlog

## Current Status Sync
(autogenerated)

MD
fi

# Ensure status exists
if [ ! -f "$STATUS_FILE" ]; then
  echo "❌ current status file not found. Run scripts/Z_FUllReposteverything.sh first."
  exit 1
fi

# Remove old sync block if exists
TMP_FILE="$(mktemp)"
awk '
  BEGIN{skip=0}
  /^## Current Status Sync/{skip=1; next}
  skip==1 && /^## /{skip=0}
  skip==0{print}
' "$BACKLOG_FILE" > "$TMP_FILE"

# Append fresh sync block
cat >> "$TMP_FILE" <<'MD'

## Current Status Sync
آخرین همگام‌سازی بکلاگ با وضعیت موجود Student UI Phase 1:

MD

cat "$STATUS_FILE" >> "$TMP_FILE"

mv "$TMP_FILE" "$BACKLOG_FILE"

echo "✅ Backlog synced with current status:"
echo "   $BACKLOG_FILE"
